#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

# set -e

echo -e "Loading \033[1;34mNGSI-LD\033[0m data using the '"${TUTORIAL_DATA_MODELS_CONTEXT}"' schema."
printf "⏳ Loading context data "

#
# Create Streetlight Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Streetlight:streetlight:mexico:4000",
    "type": "Streetlight",
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -3.16448559171566,
                40.62785133667362
            ]
        }
    },
    "areaServed": {
        "type": "Property",
        "value": "City park"
    },
    "status": {
        "type": "Property",
        "value": "ok"
    },
    "refStreetlightModel": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:StreetlightModel:streetlightmodel:STEEL_Tubular_10m"
    },
    "circuit": {
        "type": "Property",
        "value": "C-456-A467"
    },
    "lanternHeight": {
        "type": "Property",
        "value": 10
    },
    "locationCategory": {
        "type": "Property",
        "value": "centralIsland"
    },
    "powerState": {
        "type": "Property",
        "value": "off"
    },
    "controllingMethod": {
        "type": "Property",
        "value": "individual"
    },
    "dateLastLampChange": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2016-07-08T08:02:21.753Z"
        }
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567",
    "type": "Streetlight",
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -3.164485591715449,
                40.62785133667262
            ]
        }
    },
    "areaServed": {
        "type": "Property",
        "value": "Roundabouts city entrance"
    },
    "status": {
        "type": "Property",
        "value": "ok"
    },
    "refStreetlightGroup": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:StreetlightGroup:streetlightgroup:G345"
    },
    "refStreetlightModel": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:StreetlightModel:streetlightmodel:STEEL_Tubular_10m"
    },
    "circuit": {
        "type": "Property",
        "value": "C-456-A467"
    },
    "lanternHeight": {
        "type": "Property",
        "value": 10
    },
    "locationCategory": {
        "type": "Property",
        "value": "centralIsland"
    },
    "powerState": {
        "type": "Property",
        "value": "off"
    },
    "controllingMethod": {
        "type": "Property",
        "value": "individual"
    },
    "dateLastLampChange": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2016-07-08T08:02:21.753Z"
        }
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000",
    "type": "Streetlight",
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -3.16448557171566,
                40.62785135667362
            ]
        }
    },
    "areaServed": {
        "type": "Property",
        "value": "City Center"
    },
    "status": {
        "type": "Property",
        "value": "ok"
    },
    "refStreetlightModel": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:StreetlightModel:streetlightmodel:STEEL_Tubular_10m"
    },
    "circuit": {
        "type": "Property",
        "value": "C-456-A467"
    },
    "lanternHeight": {
        "type": "Property",
        "value": 10
    },
    "locationCategory": {
        "type": "Property",
        "value": "centralIsland"
    },
    "powerState": {
        "type": "Property",
        "value": "off"
    },
    "controllingMethod": {
        "type": "Property",
        "value": "individual"
    },
    "dateLastLampChange": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2016-07-08T08:02:21.753Z"
        }
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'


curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Streetlight:streetlight:mexico:9000",
    "type": "Streetlight",
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -3.164585591715449,
                40.62885133667262
            ]
        }
    },
    "areaServed": {
        "type": "Property",
        "value": "Roundabouts city entrance"
    },
    "status": {
        "type": "Property",
        "value": "ok"
    },
    "refStreetlightModel": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:StreetlightModel:streetlightmodel:STEEL_Tubular_10m"
    },
    "circuit": {
        "type": "Property",
        "value": "C-456-A467"
    },
    "lanternHeight": {
        "type": "Property",
        "value": 10
    },
    "locationCategory": {
        "type": "Property",
        "value": "centralIsland"
    },
    "powerState": {
        "type": "Property",
        "value": "off"
    },
    "controllingMethod": {
        "type": "Property",
        "value": "individual"
    },
    "dateLastLampChange": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2016-07-08T08:02:21.753Z"
        }
    },
    "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
#
# Create a series of Shelf Entities and to be placed in each Store.
# Each shelf is designed to hold one product.
#



curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit001",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.3986112,52.554699]}
    },
    "maxCapacity": {"type": "Property", "value": 50},
    "numberOfItems": {"type": "Property", "value": 50},
    "name": {"type": "Property", "value": "Corner Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:001"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit002",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.3987221,52.554664]}
    },
    "maxCapacity": {"type": "Property", "value": 100},
    "name": {"type": "Property", "value": "Wall Unit 1"},
    "numberOfItems": {"type": "Property", "value": 50},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:003"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit003",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.3987221,52.554664]}
    },
    "maxCapacity": {"type": "Property", "value": 100},
    "name": {"type": "Property", "value": "Wall Unit 2"},
    "numberOfItems": {"type": "Property", "value": 50},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:004"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit004",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.390311,52.507522]}
    },
    "maxCapacity": {"type": "Property", "value": 50},
    "numberOfItems": {"type": "Property", "value": 15},
    "name": {"type": "Property", "value": "Corner Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:001"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4000",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit005",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.390309,52.50751]}
    },
    "maxCapacity": {"type": "Property", "value": 100},
    "numberOfItems": {"type": "Property", "value": 15},
    "name": {"type": "Property", "value": "Long Wall Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:002"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4000",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'


curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit006",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.4447112,52.503199]}
    },
    "maxCapacity": {"type": "Property", "value": 50},
    "numberOfItems": {"type": "Property", "value": 15},
    "name": {"type": "Property", "value": "Corner Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:001"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit007",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.4447221,52.503164]}
    },
    "maxCapacity": {"type": "Property", "value": 100},
    "numberOfItems": {"type": "Property", "value": 50},
    "name": {"type": "Property", "value": "Wall Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:008"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit008",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.4447221,52.503164]}
    },
    "maxCapacity": {"type": "Property", "value": 100},
    "numberOfItems": {"type": "Property", "value": 50},
    "name": {"type": "Property", "value": "Wall Unit 2"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:009"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit009",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.444711,52.503122]}
    },
    "maxCapacity": {"type": "Property", "value": 50},
    "numberOfItems": {"type": "Property", "value": 50},
    "name": {"type": "Property", "value": "Corner Unit"},
    "stocks": {
      "type": "Relationship", "object": "urn:ngsi-ld:Product:009"
    },
    "locatedIn" : {
      "type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:9000",
      "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
      "installedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:employee001"},
      "statusOfWork": {"type": "Property", "value": "completed"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit010",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.4094111,52.5208028]}
    },
    "maxCapacity": {"type": "Property", "value": 200},
    "name": {"type": "Property", "value": "Long Wall Unit"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'


#
# Create a series of Product Entities. 
# These are a series of alcoholc and non-alcoholic drinks which are available to sell.
#

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:001",
    "type": "Product",
    "price": {"type": "Property", "value": 0.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "S"},
    "name": {"type": "Property", "value": "Beer"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:002",
    "type": "Product",
    "price": {"type": "Property", "value": 10.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "M"},
    "name": {"type": "Property", "value": "Red Wine"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:003",
    "type": "Product",
    "price": {"type": "Property", "value": 14.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "M"},
    "name": {"type": "Property", "value": "White Wine"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:004",
    "type": "Product",
    "price": {"type": "Property", "value": 50.00, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "XL"},
    "name": {"type": "Property", "value": "Vodka"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:005",
    "type": "Product",
    "price": {"type": "Property", "value": 0.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "S"},
    "name": {"type": "Property", "value": "Lager"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:006",
    "type": "Product",
    "price": {"type": "Property", "value": 0.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "S"},
    "name": {"type": "Property", "value": "Whisky"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:007",
    "type": "Product",
    "price": {"type": "Property", "value": 0.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "S"},
    "name": {"type": "Property", "value": "Gin"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:008",
    "type": "Product",
    "price": {"type": "Property", "value": 0.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "S"},
    "name": {"type": "Property", "value": "Apple Juice"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Product:009",
    "type": "Product",
    "price": {"type": "Property", "value": 0.99, 
      "currency": {"type": "Property", "value": "EUR"}},
    "size": {"type": "Property", "value": "S"},
    "name": {"type": "Property", "value": "Orange Juice"},
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'


#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:001
#

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:001",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:001"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:002",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:003"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:003",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4567"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:004"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:002
#
curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:004",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4000"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:001"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:005",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:4000"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:002"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:003
# Note that Shelf Unit009 is currently unused
#
curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:006",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:001"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:007",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:008"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'

curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:008",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:5000"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:009"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:004
#
curl -s -o /dev/null -X POST \
  'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entities/' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:StockOrder:010",
    "type": "StockOrder",
    "requestedFor": {"type": "Relationship", "object": "urn:ngsi-ld:Streetlight:streetlight:mexico:9000"},
    "requestedBy": {"type": "Relationship", "object": "urn:ngsi-ld:Person:bob-the-manager"},
    "orderedProduct": {"type": "Relationship", "object": "urn:ngsi-ld:Product:001"},
    "stockCount": {"type": "Property", "value": 10000},
    "orderDate": {
      "type": "Property", 
      "value": { "@type": "DateTime", "@value": "2018-08-07T12:00:00Z"}
    },
    "@context": "'"${TUTORIAL_DATA_MODELS_CONTEXT}"'"
}'



echo -e " \033[1;32mStreetlight and entities create successfully!!\033[0m"
