#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

#
# Create four Store Entities in various locations across Berlin
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
        {
           "id":"urn:ngsi-ld:Streetlight:streetlight:001",
           "type":"Streetlight",
           "location":{
                  "type":"geo:json",
                  "value":{
                         "type":"Point",
                         "coordinates":[
                                13.3986,
                                52.5547
                         ]
                  }
           },
           "address":{
                  "type":"PostalAddress",
                  "value":{
                         "streetAddress":"2, Connaught Place",
                         "addressRegion":"Delhi",
                         "addressLocality":"New Delhi",
                         "postalCode":"110001"
                  }
           },
           "name":{
                  "type":"Text",
                  "value":"Streelight 1"
           },
           "areaServed":{
                  "type":"Property",
                  "value":"Connaught Place 1"
           },
           "status":{
                  "type":"Property",
                  "value":"ok"
           },
           "circuit":{
                  "type":"Property",
                  "value":"C-456-A467"
           },
           "lanternHeight":{
                  "type":"Property",
                  "value":10
           },
           "locationCategory":{
                  "type":"Property",
                  "value":"centralIsland"
           },
           "powerState":{
                  "type":"Property",
                  "value":"off"
           },
           "controllingMethod":{
                  "type":"Property",
                  "value":"individual"
           },
           "dateLastLampChange":{
                  "type":"Property",
                  "value":{
                         "datetime":"2016-07-08T08:02:21.753Z"
                  }
           }
        },
                {
           "id":"urn:ngsi-ld:Streetlight:streetlight:002",
           "type":"Streetlight",
           "location":{
                  "type":"geo:json",
                  "value":{
                         "type":"Point",
                         "coordinates":[
                                13.3903,
                                52.5075
                         ]
                  }
           },
           "address":{
                  "type":"PostalAddress",
                  "value":{
                         "streetAddress":"7, IGI Terminal1",
                         "addressRegion":"New Delhi",
                         "addressLocality":"IGI Airport",
                         "postalCode":"110003"
                  }
           },
           "name":{
                  "type":"Text",
                  "value":"Streelight 2"
           },
           "areaServed":{
                  "type":"Property",
                  "value":"IGI Airport"
           },
           "status":{
                  "type":"Property",
                  "value":"ok"
           },
           "circuit":{
                  "type":"Property",
                  "value":"C-456-A467"
           },
           "lanternHeight":{
                  "type":"Property",
                  "value":10
           },
           "locationCategory":{
                  "type":"Property",
                  "value":"Airport"
           },
           "powerState":{
                  "type":"Property",
                  "value":"off"
           },
           "controllingMethod":{
                  "type":"Property",
                  "value":"individual"
           },
           "dateLastLampChange":{
                  "type":"Property",
                  "value":{
                         "datetime":"2017-07-18T08:02:21.753Z"
                  }
           }
        }

  ]
}'

#
# Add Weather and Twitter Responses for Store 1 using random values
#
curl -s -o /dev/null POST \
  http://orion:1026/v2/registrations \
  -H 'Content-Type: application/json' \
  -d '{
   "description": "Weather Conditions",   
   "dataProvided": {
     "entities": [
       {
         "id" : "urn:ngsi-ld:Streetlight:streetlight:001",
         "type": "Store"
       }
     ],
     "attrs": [
      "temperature", "relativeHumidity"
    ]
   },
   "provider": {
     "http": {
       "url": "http://context-provider:3000/proxy/v1/random/weatherConditions"
     },
     "legacyForwarding": true
   },
   "status": "active"
}'

curl -s -o /dev/null POST \
  http://orion:1026/v2/registrations \
  -H 'Content-Type: application/json' \
  -d '{
   "description": "Tweeting Cat Facts",
   "dataProvided": {
     "entities": [
       {
         "id" : "urn:ngsi-ld:Streetlight:streetlight:001",
         "type": "Store"
       }
     ],
     "attrs": [
      "tweets"
    ]
   },
   "provider": {
     "http": {
       "url": "http://context-provider:3000/proxy/v1/catfacts/tweets"
     },
     "legacyForwarding": true
   },
   "status": "active"
}'


# Add Weather and Twitter Responses for Store 2 using real sources
#
# curl -s -o /dev/null POST \
#   'http://orion:1026/v2/registrations' \
#   -H 'Content-Type: application/json' \
#   -d '{
#   "description": "Store:002 - Real Temperature and Humidity",
#   "dataProvided": {
#     "entities": [
#       {
#         "id": "urn:ngsi-ld:Streetlight:streetlight:002",
#         "type": "Store"
#       }
#     ],
#     "attrs": [
#       "temperature",
#       "relativeHumidity"
#     ]
#   },
#   "provider": {
#     "http": {
#       "url": "http://context-provider:3000/proxy/weather/number/temperature:temp,relativeHumidity:humidity/berlin%2cde"
#     },
#      "legacyForwarding": true
#   }
# }'

# curl -s -o /dev/null POST \
#   'http://orion:1026/v2/registrations' \
#   -H 'Content-Type: application/json' \
#   -d '{
#   "description": "Store:002 Real Tweets",
#   "dataProvided": {
#     "entities": [
#       {
#         "id": "urn:ngsi-ld:Streetlight:streetlight:002",
#         "type": "Store"
#       }
#     ],
#     "attrs": [
#       "tweets"
#     ]
#   },
#   "provider": {
#     "http": {
#       "url": "http://context-provider:3000/proxy/twitter/list/tweets:text/FIWARE"
#     },
#      "legacyForwarding": true
#   }
# }'

#
# Create a series of Shelf Entities and place the in each Store.
# Each shelf is designed to hold one product.
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
	{
  		"id":"urn:ngsi-ld:Shelf:unit001","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3986112,52.554699]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit002","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3987221,52.554664]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit003","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3987221,52.554664]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit004","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.390311,52.507522]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:002"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit005","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.390309,52.50751]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Long Wall Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:002"}
  	},
  	{
  		"id":"urn:ngsi-ld:Shelf:unit006","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447112,52.503199]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit007","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447221,52.503164]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit008","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447221,52.503164]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit009","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.444711,52.503122]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit010","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4094111,52.5208028]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Long Wall Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:004"}
  	}
  ]
}'

#
# Create a series of Product Entities. 
# These are a series of alcoholc and non-alcoholic drinks which are available to sell.
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
    {
      "id":"urn:ngsi-ld:Product:001", "type":"Product",
      "name":{"type":"Text", "value":"Beer"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:002", "type":"Product",
      "name":{"type":"Text", "value":"Red Wine"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 1099}
    },
    {
      "id":"urn:ngsi-ld:Product:003", "type":"Product",
      "name":{"type":"Text", "value":"White Wine"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 1499}
    },
    {
      "id":"urn:ngsi-ld:Product:004", "type":"Product",
      "name":{"type":"Text", "value":"Vodka"},
      "size":{"type":"Text", "value": "XL"},
      "price":{"type":"Integer", "value": 5000}
    },
    {
      "id":"urn:ngsi-ld:Product:005", "type":"Product",
      "name":{"type":"Text", "value":"Lager"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:006", "type":"Product",
      "name":{"type":"Text", "value":"Whisky"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:007", "type":"Product",
      "name":{"type":"Text", "value":"Gin"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:008", "type":"Product",
      "name":{"type":"Text", "value":"Apple Juice"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:009", "type":"Product",
      "name":{"type":"Text", "value":"Orange Juice"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    }
  ]
}'


#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:001
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:001","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit001"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:002","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit002"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:003"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:003","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit003"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:004"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:002
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:004","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit004"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:005","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit005"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:002"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	}
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:003
# Note that Shelf Unit009 is currently unused
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:006","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit006"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:007","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit007"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:008"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:008","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit008"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:009"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:004
#
curl -s -o /dev/null POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:401","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Streetlight:streetlight:004"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit010"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'

echo -e " \033[1;32mStreetlights created successfully\033[0m"
